name: Matrix Build

on:
  workflow_dispatch:

jobs:
  build:                     # ← مسافتين بعد jobs
    runs-on: ${{ matrix.os }}   # ← تحت build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]

    steps:
      - uses: actions/checkout@v4
      - name: Print environment
        run: |
          echo "Running on ${{ matrix.os }}"
          echo "Node version ${{ matrix.node }}"
     - name: Print environment
       run: |
         node -v
         echo "OS: $RUNNER_OS"
